from . import edi_backend
from . import product_template
from . import account_invoice
from . import agreement_type
from . import agreement_rebate_settlement
from . import edi_unilever_agreement
from . import edi_unilever_agreement_condition
from . import edi_unilever_data
from . import edi_unilever_rappel_group
from . import partner_delivery_zone
from . import product
from . import product_brand
from . import res_company
from . import res_config_settings
from . import res_partner
from . import sale_order
from . import stock_move
from . import stock_move_line
from . import stock_picking
from . import stock_picking_type
from . import stock_production_lot
from . import stock_scrap
from . import unilever_invoice_refund
