# Copyright 2018 Tecnativa - Sergio Teruel
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
{
    "name": "EDI Backend Unilever",
    "summary": "Edi backend for unilever",
    "version": "16.0.1.0.0",
    "development_status": "Production/Stable",
    "category": "Product",
    "website": "https://github.com/Tecnativa/extra-addons",
    "author": "Tecnativa",
    "license": "AGPL-3",
    "external_dependencies": {"python": ["xlrd", "openupgradelib"]},
    "depends": [
        "base_edi_backend",
        "product_expiry",
        "purchase_stock",
        "agreement_unilever_mef",
        "agreement_rebate",
        "l10n_es_aeat",
        "l10n_es_partner",
        "sale_order_line_input",
        "sale_stock",
        "queue_job",
        "partner_company_group",
        "partner_pricelist_search",
        "product_brand",
        "product_pricelist_by_contact",  # for viewing specific pricelists per contact
        "report_xlsx",
        "sale_order_qty_change_no_recompute",  # for proper onchange triggering
        "sale_partner_company_group",
        "stock_picking_report_valued",
        "stock_picking_show_return",
        "partner_delivery_zone",
        "website_sale_wishlist",
        # TODO: Move to edi_unilever? TT41737
        # Depends added only for get partner_shipping_id from invoice report needed for
        # Unilever settlements
        "congeladosromero_custom",
    ],
    "data": [
        "security/edi_unilever_security.xml",
        "security/ir.model.access.csv",
        "data/edi_backend_ulv_import.xml",
        "data/edi_backend_config_prod.xml",
        "data/edi_backend_config_abo.xml",
        "data/edi_unilever_data.xml",
        "data/edi_unilever_agrement_type_data.xml",
        "data/edi_unilever_export_alb.xml",
        "data/edi_unilever_export_cli.xml",
        "data/edi_unilever_export_ven_pick.xml",
        "data/edi_unilever_export_dto.xml",
        "data/edi_unilever_export_food_solutions.xml",
        "data/edi_unilever_export_col.xml",
        "data/edi_unilever_export_mef.xml",
        "data/edi_unilever_export_pol.xml",
        "data/edi_unilever_export_pol_liq.xml",
        "data/edi_backend_ulv.xml",
        "data/gescon_data.xml",
        "data/report_paperformat.xml",
        "report/mef_report_concession_templates.xml",
        "report/mef_report_recession_templates.xml",
        "report/report_deliveryslip.xml",
        "report/report_settlement_xlsx.xml",
        "report/report_stockpicking_opreation.xml",
        "report/report_agreement_pol_liquida.xml",
        "report/report_recount_pending_freezers.xml",
        "report/report_recount_pending_freezers_xlsx.xml",
        # 'report/unilever_fresh_asset_report.xml',
        "views/edi_backend_view.xml",
        "views/edi_backend_communication_history_view.xml",
        "views/product_template_view.xml",
        "views/agreement_rebate_settlement_view.xml",
        "views/edi_unilever_agreement_view.xml",
        "views/edi_unilever_agreement_communication_view.xml",
        "views/edi_unilever_agreement_condition_view.xml",
        "views/edi_unilever_data_view.xml",
        "views/edi_unilever_rappel_group_view.xml",
        "views/partner_delivery_zone_view.xml",
        "views/product_brand_view.xml",
        "views/product_view.xml",
        "views/res_company_view.xml",
        "views/res_config_settings_views.xml",
        "views/res_partner_view.xml",
        "views/sale_order_view.xml",
        "views/stock_move_view.xml",
        "views/stock_picking_view.xml",
        "views/stock_picking_type_view.xml",
        "views/stock_production_lot_views.xml",
        "views/unilever_payment_invoice_views.xml",
        "wizard/agreement_duplicate_wizard_view.xml",
        "wizard/gescon_import_xls_view.xml",
        "wizard/edi_unilever_report_views.xml",
        "wizard/settlement_create_views.xml",
        "report/report_settlements.xml",
        "report/report_invoice_discounts.xml",
        "report/report_year_bonus.xml",
        "report/report_rappel_conditions.xml",
        "report/report_rappel.xml",
        "report/report_gira.xml",
        "report/report_gira_summary.xml",
        "report/report_gira_detailed.xml",
        # Respect this order for menu file
        "views/edi_unilever_menu.xml",
        "wizard/data_integrity_wiz_view.xml",
    ],
    "assets": {
        "web.report_assets_common": [
            "edi_backend_ulv/static/src/css/report_style.css",
        ],
    },
    "application": False,
    "installable": False,
}
